export const defaultIgnore = [
    "**/node_modules/",
    "**/.cache",
    "**/dist/",
    "**/build/",
    "**/coverage/",
    "**/tmp/",
    "**/temp/",
    "**/out/",
    "**/output/",
    "**/logs/",
    "**/lcov-report/",
    "**/artifacts/",
    "**/*.log",
    "**/*.min.js",
    "**/*.bundle.js",
    "**/*.config.js",
    "**/*.test.js",
    "**/*.spec.js",
    "**/*.d.ts",
    "**/*.snap",
    "**/*.map",
    "**/vendor/",
    "**/bin/",
    "**/obj/",
    "**/.npm/",
    "**/.yarn/",
    "**/.pnp/",
    "**/.next/",
    "**/.nuxt/",
    "**/.parcel-cache/",
    "**/.eslintcache/",
    "**/.jest/",
    "**/.cache-loader/",

    "*.config.ts",
    "*.config.js",
    "*.config.cjs",
    "*.config.mjs",
    "vitest.setup.mjs",
    "vitest.setup.js",
    "vitest.setup.ts",
];

export const defaultIgnoreConfig = {
    ignores: defaultIgnore,
};
